#spring.application.name=Arbodat+

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
#checks the existing database structure when the Spring application is started
#and compares it with the entities defined in the application. If differences
#are detected, the database structure is adjusted accordingly


# Multipart file settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=250MB
spring.servlet.multipart.max-request-size=250MB